# cargo

# [[file:~/Workspace/Programming/gosh-rs/database/database.note::*cargo][cargo:1]]
[package]
name = "gosh-db"
version = "0.0.1"
edition = "2018"
authors = ["Wenping Guo <ybyygu@gmail.com>"]

[dependencies]
structopt = "0.2"
quicli = "0.4"
diesel = { version = "1.4", features = ["sqlite"] }
diesel_migrations = "1.0"
dotenv = "0.10"
serde = {version="1.0", features = ["derive"]}
serde_json = "1.0"
bincode = "1.0"
gosh-models = {version = "*", path = "../models"}
gchemol = {git = "https://github.com/ybyygu/gchemol.git", tag="v0.0.34"}

[dev-dependencies]
# cargo:1 ends here
